/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c IMSettingsQtDBusAdaptor -a qt-imsettings-glue ./introspection.xml com.redhat.imsettings.Qt
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "qt-imsettings-glue.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class IMSettingsQtDBusAdaptor
 */

IMSettingsQtDBusAdaptor::IMSettingsQtDBusAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

IMSettingsQtDBusAdaptor::~IMSettingsQtDBusAdaptor()
{
    // destructor
}

bool IMSettingsQtDBusAdaptor::ChangeTo(const QString &module)
{
    // handle method call com.redhat.imsettings.Qt.ChangeTo
    bool ret;
    QMetaObject::invokeMethod(parent(), "ChangeTo", Q_RETURN_ARG(bool, ret), Q_ARG(QString, module));
    return ret;
}

