/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c IMSettingsQtDBusAdaptor -a qt-imsettings-glue ./introspection.xml com.redhat.imsettings.Qt
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef QT-IMSETTINGS-GLUE_H_1269313308
#define QT-IMSETTINGS-GLUE_H_1269313308

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.redhat.imsettings.Qt
 */
class IMSettingsQtDBusAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.redhat.imsettings.Qt")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.redhat.imsettings.Qt\">\n"
"    <method name=\"ChangeTo\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"module\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"ret\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    IMSettingsQtDBusAdaptor(QObject *parent);
    virtual ~IMSettingsQtDBusAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool ChangeTo(const QString &module);
Q_SIGNALS: // SIGNALS
};

#endif
